# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('attachment', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('status', models.IntegerField(choices=[(1, 'Live'), (2, 'Finished'), (3, 'Hidden')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Срочно'), (2, 'Запланированный'), (3, 'Бессрочный')], default=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
